# Example docker compose, update the image name and the database properties to the ones you need
version: '3'
services: 
  db:
    image: postgres
    container_name: 'postgres'
    restart: always
    environment:
      POSTGRES_PASSWORD: ticket
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data 